version: "3"

services:

    api-mercadinho:
        image: registry.digitalocean.com/dcr-samuel/puc-mercadinho-api:${TAG}
        container_name: puc-mercadinho-api
        build: 
            context: Puc.Mercadinho
            dockerfile: ./Puc.Mercadinho.Api/Dockerfile
            args:
                MY_TAG: ${{ github.sha }}
        ports:
            - "5001:5001"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
